#!/usr/bin/env python3
"""Generate manuscript numbers, tables and figures from immutable data + correction JSON."""
from pathlib import Path
import json
import os
import statistics as st
import numpy as np
os.environ.setdefault('MPLCONFIGDIR', str(Path(__file__).resolve().parent / '.cache/matplotlib'))
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch

PAPER=Path(__file__).resolve().parent
ROOT=PAPER.parent
out=PAPER/'generated'; out.mkdir(exist_ok=True)
figdir=PAPER/'figures'
r=json.loads((PAPER/'revision/results.json').read_text())
data=json.loads((ROOT/'analysis/e1_dataset_main.json').read_text())['pairs']
c=r['corrections']['H1_cost']; q=r['corrections']['H3_quality']; t=r['H2_time']
def interval(values): return '['+',\\,'.join(f'{100*x:+.2f}' for x in values)+']'
macros=dict(CostMedian=f"{100*c['median_relative_diff']:.2f}",CostP=f"{c['p_value']:.4f}",
 CostCI=interval(c['ci95_relative_diff']),TimeRatio=f"{t['ratio_point']:.4f}",TimeUpper=f"{t['ratio_ci_upper']:.4f}",
 QualityLower=f"{q['ci90_lower_pp']:.2f}",QualityDiff=f"{q['diff_pp']:.2f}",
 QualityExact=f"{r['supplementary']['conservative_exact_quality_lower_pp']:.2f}",
 StratifiedCI=interval(r['supplementary']['fixed_spec_percentile_ci95']),
 TotalB=f"{r['totals']['B']:.2f}",TotalC=f"{r['totals']['C']:.2f}",
 TotalIncrease=f"{100*r['totals']['relative_difference']:.2f}",
 GapSeconds=f"{r['timing']['gap_median']*60:.2f}",GapMax=f"{r['timing']['gap_max']:.2f}")
(out/'numbers.tex').write_text('% Generated by render_assets.py; do not hand-edit.\n'+''.join('\\newcommand{\\'+k+'}{'+v+'}\n' for k,v in macros.items()))
rows=r['H4b']['rows']
ordered=sorted(rows,key=lambda v:v['median_relative_diff'])
(out/'spec_rows.tex').write_text('\\begin{tabular}{lrrrr}\n\\toprule 仕様 & B中央値 & C中央値 & 相対差中央値 & Cが安い対\\\\\\midrule\n'+''.join(
 '\\spec{'+v['spec']+'} & '+f"{v['cost_B_median']:.4f} & {v['cost_C_median']:.4f} & ${100*v['median_relative_diff']:+.1f}$\\% & {v['cheaper']}/14 \\\\\n" for v in ordered)+'\\bottomrule\n\\end{tabular}\n')
(out/'model_rows.tex').write_text('\\begin{tabular}{lrrrl}\n\\toprule 仕様 & 実測$r_s$ & 予測$\\widehat r_s$ & 相対誤差 & 25\\%以内\\\\\\midrule\n'+''.join(
 '\\spec{'+v['spec']+'} & '+f"{v['r_observed']:.4f} & {v['r_hat']:.4f} & ${100*v['relative_error']:+.1f}$\\% & "+('はい' if abs(v['relative_error'])<=.25 else 'いいえ')+' \\\\\n' for v in rows)+'\\bottomrule\n\\end{tabular}\n')
plt.rcParams.update({'font.size':10,'axes.spines.top':False,'axes.spines.right':False,'pdf.fonttype':42,'savefig.bbox':'tight'})
blue='#245a83'; orange='#c16a2f'; gray='#6b7280'
def save(fig,name):
 for ext in ['pdf','png']: fig.savefig(figdir/(name+'.'+ext),dpi=180)
 plt.close(fig)

rel=np.array([100*(p['cost_C']-p['cost_B'])/p['cost_B'] for p in data])
fig,ax=plt.subplots(figsize=(7.2,3.6))
ax.hist(rel,bins=24,color=blue,alpha=.85,edgecolor='white')
ax.axvline(0,color=gray,lw=1)
ax.axvline(np.median(rel),color=orange,ls='--',label=f'Median: {np.median(rel):+.2f}%')
ax.axvline(-20,color='#34774a',ls=':',lw=2,label='Pre-specified reduction threshold: -20%')
ax.set(xlabel='Paired relative cost difference (C - B) / B [%]',ylabel='Number of pairs')
ax.legend(frameon=False,fontsize=9); fig.tight_layout();save(fig,'revision_distribution')

fig,ax=plt.subplots(figsize=(8,4.2))
names=[v['spec'] for v in ordered]
values=[[100*(p['cost_C']-p['cost_B'])/p['cost_B'] for p in data if p['spec']==s] for s in names]
bp=ax.boxplot(values,orientation='horizontal',tick_labels=names,showfliers=False,patch_artist=True,widths=.5,
              medianprops={'color':'black','linewidth':1.3})
for patch,s in zip(bp['boxes'],names):patch.set_facecolor(orange if s=='ct_library' else blue);patch.set_alpha(.2)
for i,(s,v) in enumerate(zip(names,values),1):
 offsets=np.linspace(-.12,.12,len(v))
 ax.scatter(v,i+offsets,s=17,color=orange if s=='ct_library' else blue,alpha=.8,zorder=3)
ax.axvline(0,color=gray,lw=1);ax.set_xlabel('Paired relative cost difference (C - B) / B [%]')
ax.grid(axis='x',alpha=.15);fig.tight_layout();save(fig,'revision_per_spec')

fig,ax=plt.subplots(figsize=(8,4))
for i,v in enumerate(rows):
 ax.plot([v['r_observed'],v['r_hat']],[i,i],color='#bdc5cc',lw=2)
 ax.scatter(v['r_observed'],i,c=blue,s=45,label='Observed total-cost ratio' if i==0 else None,zorder=3)
 ax.scatter(v['r_hat'],i,c=orange,s=48,marker='D',label='Frozen prediction' if i==0 else None,zorder=3)
ax.set_yticks(range(len(rows)),[v['spec'] for v in rows]);ax.invert_yaxis()
ax.axvline(1,color=gray,ls='--',lw=1);ax.set(xlim=(.85,1.64),xlabel='Cost ratio C / B (1 = equal total cost)')
ax.legend(frameon=False,loc='upper center',bbox_to_anchor=(.5,1.16),ncol=2,fontsize=9)
ax.grid(axis='x',alpha=.15);fig.tight_layout();save(fig,'revision_model')

fig,axes=plt.subplots(1,2,figsize=(8,3.8),gridspec_kw={'width_ratios':[1,1.7]})
ax=axes[0]; ax.set_xlim(-.6,2.6);ax.set_ylim(-1.1,1.5);ax.axis('off')
for x,s in zip([0,1,2],['A','B','C']):
 ax.scatter(x,.35,s=1050,color=blue,zorder=3);ax.text(x,.35,s,color='white',ha='center',va='center',weight='bold',fontsize=13)
for a,b in [(0,1),(1,2)]:ax.plot([a,b],[.35,.35],color=gray,lw=3)
ax.text(1,1.15,'Declared write-scope overlap',ha='center',fontsize=10)
ax.text(1,-.35,'A and C do not overlap',ha='center',fontsize=10)
ax.text(1,-.8,'One connected component',ha='center',fontsize=10,color=orange)
ax=axes[1];ax.set_xlim(0,3.2);ax.set_ylim(-.6,3.5)
for y,start,txt,col in [(2.7,0,'Task A',blue),(2.05,0,'Task C',blue),(2.7,1,'Task B',blue),(.45,0,'Task A',orange),(.45,1,'Task B',orange),(.45,2,'Task C',orange)]:
 ax.barh(y,.94,left=start,height=.46,color=col);ax.text(start+.47,y,txt,color='white',ha='center',va='center',fontsize=9)
ax.text(0,3.2,'Policy B: fresh sessions; direct conflicts only',fontsize=9)
ax.text(0,1.13,'Policy C: one continued lane',fontsize=9)
ax.set_yticks([]);ax.set_xticks([0,1,2,3]);ax.set_xlabel('Illustrative time units (not measured)')
ax.spines['left'].set_visible(False);fig.tight_layout();save(fig,'revision_lane_structure')
print('Generated numeric macros, 2 tables, and 4 figures from recorded data.')
