#!/usr/bin/env python3
"""Generate manuscript numbers, tables and figures from immutable data + correction JSON."""
from pathlib import Path
import json
import re
import os
import statistics as st
import numpy as np
os.environ.setdefault('MPLCONFIGDIR', str(Path(__file__).resolve().parent / '.cache/matplotlib'))
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch

PAPER=Path(__file__).resolve().parent
ROOT=PAPER.parent
out=PAPER/'generated'; out.mkdir(exist_ok=True)
figdir=PAPER/'figures'
r=json.loads((PAPER/'revision/results.json').read_text())
data=json.loads((ROOT/'analysis/e1_dataset_main.json').read_text())['pairs']
c=r['corrections']['H1_cost']; q=r['corrections']['H3_quality']; t=r['H2_time']
def interval(values): return '\\ensuremath{['+',\\,'.join(f'{100*x:+.2f}' for x in values)+']}'
def signed(v): return '\\ensuremath{'+v+'}' if v.startswith('-') else v
def macro_lines(d): return ''.join('\\newcommand{\\'+k+'}{'+signed(v)+'}\n' for k,v in d.items())
def minus(s): return re.sub(r'-(?=\d)','\u2212',s)  # sign only; keeps hyphenated words intact
macros=dict(CostMedian=f"{100*c['median_relative_diff']:.2f}",CostP=f"{c['p_value']:.4f}",
 CostCI=interval(c['ci95_relative_diff']),TimeRatio=f"{t['ratio_point']:.4f}",TimeUpper=f"{t['ratio_ci_upper']:.4f}",
 QualityLower=f"{q['ci90_lower_pp']:.2f}",QualityDiff=f"{q['diff_pp']:.2f}",
 QualityExact=f"{r['supplementary']['conservative_exact_quality_lower_pp']:.2f}",
 StratifiedCI=interval(r['supplementary']['fixed_spec_percentile_ci95']),
 TotalB=f"{r['totals']['B']:.2f}",TotalC=f"{r['totals']['C']:.2f}",
 TotalIncrease=f"{100*r['totals']['relative_difference']:.2f}",
 GapSeconds=f"{r['timing']['gap_median']*60:.2f}",GapMax=f"{r['timing']['gap_max']:.2f}")
(out/'numbers.tex').write_text('% Generated by render_assets.py; do not hand-edit.\n'+macro_lines(macros))
rows=r['H4b']['rows']
ordered=sorted(rows,key=lambda v:v['median_relative_diff'])
(out/'spec_rows.tex').write_text('\\begin{tabular}{lrrrr}\n\\toprule 仕様 & B中央値 & C中央値 & 相対差中央値 & Cが安い対\\\\\\midrule\n'+''.join(
 '\\spec{'+v['spec']+'} & '+f"{v['cost_B_median']:.4f} & {v['cost_C_median']:.4f} & ${100*v['median_relative_diff']:+.1f}$\\% & {v['cheaper']}/14 \\\\\n" for v in ordered)+'\\bottomrule\n\\end{tabular}\n')
(out/'model_rows.tex').write_text('\\begin{tabular}{lrrrl}\n\\toprule 仕様 & 実測$r_s$ & 予測$\\widehat r_s$ & 相対誤差 & 25\\%以内\\\\\\midrule\n'+''.join(
 '\\spec{'+v['spec']+'} & '+f"{v['r_observed']:.4f} & {v['r_hat']:.4f} & ${100*v['relative_error']:+.1f}$\\% & "+('はい' if abs(v['relative_error'])<=.25 else 'いいえ')+' \\\\\n' for v in rows)+'\\bottomrule\n\\end{tabular}\n')
plt.rcParams.update({'font.size':10,'axes.spines.top':False,'axes.spines.right':False,'pdf.fonttype':42,'savefig.bbox':'tight'})
blue='#245a83'; orange='#c16a2f'; gray='#6b7280'
def save(fig,name):
 # Omit the PDF CreationDate so a rebuild is byte-identical and can be hashed in a release manifest.
 fig.savefig(figdir/(name+'.pdf'),dpi=180,metadata={'CreationDate':None})
 fig.savefig(figdir/(name+'.png'),dpi=180)
 plt.close(fig)

rel=np.array([100*(p['cost_C']-p['cost_B'])/p['cost_B'] for p in data])
fig,ax=plt.subplots(figsize=(7.2,3.6))
ax.hist(rel,bins=24,color=blue,alpha=.85,edgecolor='white')
ax.axvline(0,color=gray,lw=1)
ax.axvline(np.median(rel),color=orange,ls='--',label=minus(f'Median: {np.median(rel):+.2f}%'))
ax.axvline(-20,color='#34774a',ls=':',lw=2,label=minus('Pre-specified reduction threshold: -20%'))
ax.set(xlabel='Paired relative cost difference (C - B) / B [%]',ylabel='Number of pairs')
ax.legend(frameon=False,fontsize=9); fig.tight_layout();save(fig,'revision_distribution')

fig,ax=plt.subplots(figsize=(8,4.2))
names=[v['spec'] for v in ordered]
values=[[100*(p['cost_C']-p['cost_B'])/p['cost_B'] for p in data if p['spec']==s] for s in names]
bp=ax.boxplot(values,orientation='horizontal',tick_labels=names,showfliers=False,patch_artist=True,widths=.5,
              medianprops={'color':'black','linewidth':1.3})
for patch,s in zip(bp['boxes'],names):patch.set_facecolor(orange if s=='ct_library' else blue);patch.set_alpha(.2)
for i,(s,v) in enumerate(zip(names,values),1):
 offsets=np.linspace(-.12,.12,len(v))
 ax.scatter(v,i+offsets,s=17,color=orange if s=='ct_library' else blue,alpha=.8,zorder=3)
ax.axvline(0,color=gray,lw=1);ax.set_xlabel('Paired relative cost difference (C - B) / B [%]')
ax.grid(axis='x',alpha=.15);fig.tight_layout();save(fig,'revision_per_spec')

fig,ax=plt.subplots(figsize=(8,4))
for i,v in enumerate(rows):
 ax.plot([v['r_observed'],v['r_hat']],[i,i],color='#bdc5cc',lw=2)
 ax.scatter(v['r_observed'],i,c=blue,s=45,label='Observed total-cost ratio' if i==0 else None,zorder=3)
 ax.scatter(v['r_hat'],i,c=orange,s=48,marker='D',label='Frozen prediction' if i==0 else None,zorder=3)
ax.set_yticks(range(len(rows)),[v['spec'] for v in rows]);ax.invert_yaxis()
ax.axvline(1,color=gray,ls='--',lw=1);ax.set(xlim=(.85,1.64),xlabel='Cost ratio C / B (1 = equal total cost)')
ax.legend(frameon=False,loc='upper center',bbox_to_anchor=(.5,1.16),ncol=2,fontsize=9)
ax.grid(axis='x',alpha=.15);fig.tight_layout();save(fig,'revision_model')

fig,axes=plt.subplots(1,2,figsize=(8,3.8),gridspec_kw={'width_ratios':[1,1.7]})
ax=axes[0]; ax.set_xlim(-.6,2.6);ax.set_ylim(-1.1,1.5);ax.axis('off')
for x,s in zip([0,1,2],['A','B','C']):
 ax.scatter(x,.35,s=1050,color=blue,zorder=3);ax.text(x,.35,s,color='white',ha='center',va='center',weight='bold',fontsize=13)
for a,b in [(0,1),(1,2)]:ax.plot([a,b],[.35,.35],color=gray,lw=3)
ax.text(1,1.15,'Declared write-scope overlap',ha='center',fontsize=10)
ax.text(1,-.35,'A and C do not overlap',ha='center',fontsize=10)
ax.text(1,-.8,'One connected component',ha='center',fontsize=10,color=orange)
ax=axes[1];ax.set_xlim(0,3.2);ax.set_ylim(-.6,3.5)
for y,start,txt,col in [(2.7,0,'Task A',blue),(2.05,0,'Task C',blue),(2.7,1,'Task B',blue),(.45,0,'Task A',orange),(.45,1,'Task B',orange),(.45,2,'Task C',orange)]:
 ax.barh(y,.94,left=start,height=.46,color=col);ax.text(start+.47,y,txt,color='white',ha='center',va='center',fontsize=9)
ax.text(0,3.2,'Policy B: fresh sessions; direct conflicts only',fontsize=9)
ax.text(0,1.13,'Policy C: one continued lane',fontsize=9)
ax.set_yticks([]);ax.set_xticks([0,1,2,3]);ax.set_xlabel('Illustrative time units (not measured)')
ax.spines['left'].set_visible(False);fig.tight_layout();save(fig,'revision_lane_structure')
print('Generated numeric macros, 2 tables, and 4 figures from recorded data.')

# v0.3 post-hoc descriptions, kept distinct from the v0.2 primary results.
v3=json.loads((PAPER/'revision/v0.3/results.json').read_text())
ct=v3['accounting']['ct_library'];g=v3['groups'];sp=v3['specs']
newmacros={'SignP':f"{g['all']['sign']['p_two_sided']:.4f}",
 'NonCTSignP':f"{g['non_ct']['sign']['p_two_sided']:.4f}",
 'ControlCI':interval(g['controls']['ci95']), 'CTCI':interval(sp['ct_library']['ci95']),
 'CTDelta':f"{ct['reported_delta']:.4f}", 'CTStandardDelta':f"{ct['standardized_delta']:.4f}",
 'CTResidualDelta':f"{ct['parts']['residual']['usd_delta']:.4f}",
 'CTWriteShare':f"{100*ct['parts']['cache_creation_tokens']['usd_delta']/ct['standardized_delta']:.1f}",
 'CTReadShare':f"{100*ct['parts']['cache_read_tokens']['usd_delta']/ct['standardized_delta']:.1f}",
 'CTFirstShare':f"{100*v3['ct_tasks']['CT-A']['reported_delta']/ct['reported_delta']:.1f}",
 'CTMeanContribution':f"{100*sp['ct_library']['relative_sum']/98:.2f}",
 'NonCTMeanContribution':f"{100*g['non_ct']['relative_sum']/98:.2f}"}
anc=g['active_non_ct'];cta=v3['ct_tasks']['CT-A']['paired'];mixr=v3['model_mix']['by_reuse']
rr=v3['residual_ratio']['all'];carry={r['task']:r for r in v3['carry_check']['rows']}
newmacros.update({'ActiveNonCTMedian':f"{100*anc['median']:+.2f}",'ActiveNonCTCI':interval(anc['ci95']),
 'ActiveNonCTCheaper':f"{anc['sign']['negative']}",'ActiveNonCTP':f"{anc['sign']['p_two_sided']:.4f}",
 'AuxFresh':f"{mixr['fresh']['aux']}",'AuxResumed':f"{mixr['resumed']['single']}",
 'CallRecords':f"{v3['model_mix']['calls']}",
 'CTAMedian':f"{100*cta['median_relative_diff']:+.1f}",'CTACI':interval(cta['ci95']),
 'CTATurnUp':f"{cta['turn_sign']['positive']}",
 'ResidualRatioB':f"{rr['B']:.3f}",'ResidualRatioC':f"{rr['C']:.3f}",
 'CarryShareB':f"{100*carry['CT-B']['observed_over_assumed']:.0f}",
 'CarryShareC':f"{100*carry['CT-C']['observed_over_assumed']:.0f}",
 'SubHatFrozen':f"{v3['carry_check']['substitution']['r_hat_frozen']:.4f}",
 'SubHatObserved':f"{v3['carry_check']['substitution']['r_hat_observed_carry']:.4f}",
 'SubErrFrozen':f"{100*v3['carry_check']['substitution']['relative_error_frozen']:+.1f}",
 'SubErrObserved':f"{100*v3['carry_check']['substitution']['relative_error_observed_carry']:+.1f}",
 'ResidualDirSpecs':f"{sum(v3['residual_ratio'][k]['B']<v3['residual_ratio'][k]['C'] for k in v3['specs'])}"})

with (out/'numbers.tex').open('a') as f:f.write(macro_lines(newmacros))
# CTの機構表: ターン・文脈・ターン単価・対応差を1枚に並べる
(out/'ct_mechanism_rows.tex').write_text('\\begin{tabular}{lcrrrr}\n\\toprule タスク & Cで継続 & ターン差中央値 & 最大文脈 B$\\to$C & ターン単価比 & 費用相対差中央値\\\\\\midrule\n'+''.join(
 '\\spec{'+t+'} & '+('あり' if v3['ct_tasks'][t]['activity']['C']['resumed'] else 'なし')+' & '
 +f"${v['paired']['median_turn_delta']:+.1f}$ & {v['context']['B']:,.0f}$\\to${v['context']['C']:,.0f} & "
 +f"{v['per_turn_ratio']:.2f} & ${100*v['paired']['median_relative_diff']:+.1f}$\\% \\\\\n"
 for t,v in v3['ct_tasks'].items())+'\\bottomrule\n\\end{tabular}\n')

control_names=['s17_w_two_files','w_two_files','ct_library']
(out/'control_rows.tex').write_text('\\begin{tabular}{lrrrr}\n\\toprule 仕様 & $n$ & 相対差中央値 & BCa 95\\%区間 & USD差中央値\\\\\\midrule\n'+''.join(
 '\\spec{'+s+'} & '+f"{sp[s]['n']} & ${100*sp[s]['median']:+.1f}$\\% & ${interval(sp[s]['ci95'])}$\\% & ${sp[s]['median_usd']:+.4f}$ \\\\\n" for s in control_names)+'\\bottomrule\n\\end{tabular}\n')
labels={'input_tokens':'通常入力','output_tokens':'出力','cache_read_tokens':'cache read','cache_creation_tokens':'cache write','residual':'報告額との差（残差）'}
account_rows=[]
for k,v in ct['parts'].items():
 tokens='---' if k=='residual' else f"${v['tokens_delta']:+,}$"
 account_rows.append(labels[k]+' & '+tokens+f" & ${v['usd_B']:.4f}$ & ${v['usd_C']:.4f}$ & ${v['usd_delta']:+.4f}$ \\\\\n")
(out/'accounting_rows.tex').write_text('\\begin{tabular}{lrrrr}\n\\toprule 項目 & トークン差 & B & C & 差額\\\\\\midrule\n'+''.join(account_rows)+
 '\\midrule 報告費用 & --- & '+f"{ct['B']['cost_usd']:.4f} & {ct['C']['cost_usd']:.4f} & ${ct['reported_delta']:+.4f}$ \\\\\n"+'\\bottomrule\n\\end{tabular}\n')
(out/'ct_task_rows.tex').write_text('\\begin{tabular}{lrrrrl}\n\\toprule タスク & B費用 & C費用 & 差額 & ターン数 B/C & Cで継続\\\\\\midrule\n'+''.join(
 '\\spec{'+task+'} & '+f"{v['B']['cost_usd']:.4f} & {v['C']['cost_usd']:.4f} & ${v['reported_delta']:+.4f}$ & {v['activity']['B']['reported_turns']}/{v['activity']['C']['reported_turns']} & "+('なし' if task=='CT-A' else '14/14')+' \\\\\n' for task,v in v3['ct_tasks'].items())+'\\bottomrule\n\\end{tabular}\n')
# Visually identify structural controls without pretending their medians define a noise band.
fig,ax=plt.subplots(figsize=(8,3.4))
for i,s in enumerate(control_names):
 values=[100*(p['cost_C']-p['cost_B'])/p['cost_B'] for p in data if p['spec']==s]
 col=orange if s=='ct_library' else '#6f5a91'
 ax.scatter(values,i+np.linspace(-.1,.1,14),s=18,alpha=.6,color=col)
 lo,hi=100*np.array(sp[s]['ci95']);med=100*sp[s]['median']
 ax.plot([lo,hi],[i,i],color=col,lw=3);ax.scatter(med,i,s=50,marker='D',color=col,zorder=3)
ax.set_yticks(range(3),control_names);ax.invert_yaxis();ax.axvline(0,color=gray,lw=1)
ax.set_xlabel('Paired relative difference [%]; diamond = median, line = BCa 95% CI')
ax.grid(axis='x',alpha=.15);fig.tight_layout();save(fig,'revision_controls')
fig,axes=plt.subplots(1,2,figsize=(9,3.6),gridspec_kw={'width_ratios':[1.35,1]})
keys=['cache_creation_tokens','cache_read_tokens','output_tokens','input_tokens','residual']
ax=axes[0];vals=[ct['parts'][k]['usd_delta'] for k in keys]
ax.barh(range(5),vals,color=[orange,blue,gray,gray,'#8a718f'])
ax.set_yticks(range(5),['Cache write','Cache read','Output','Input','Residual']);ax.invert_yaxis();ax.axvline(0,color=gray,lw=1)
for i,v in enumerate(vals):ax.text(v+(0.08 if v>=0 else -.08),i,minus(f'{v:+.3f}'),va='center',ha='left' if v>=0 else 'right',fontsize=9)
ax.set(xlim=(-1.8,4.6),xlabel='C - B [USD], fixed-rate terms + residual',title='CT: additive cost accounting')
ax=axes[1];names=['Cache write','Cache read','Output','Reported turns']
ratios=[ct['C'][k]/ct['B'][k] for k in ['cache_creation_tokens','cache_read_tokens','output_tokens']]
ratios.append(v3['ct_activity']['C']['reported_turns']/v3['ct_activity']['B']['reported_turns'])
ax.barh(range(4),ratios,color=[orange,blue,gray,gray]);ax.set_yticks(range(4),names);ax.invert_yaxis();ax.axvline(1,color='black',ls='--',lw=1)
for i,v in enumerate(ratios):ax.text(v+.03,i,f'{v:.3f}',va='center',fontsize=9)
ax.set(xlim=(0,2.35),xlabel='Aggregate C / B ratio',title='CT: activity, 14 runs per arm')
fig.tight_layout();save(fig,'revision_accounting')
print('v0.3: added 3 tables and 2 figures; fixed prices remain separate from reported cost.')
